site_name: ITMO Web Dev — Поляков Александр (K3339)
site_author: Поляков Александр
site_description: Отчёты по практикам и лабораторным работам

nav:
  - Главная: index.md
  - Практика 1: pr1.md
  - Практика 2: pr2.md
  - Практика 3: pr3.md
  - Лабораторная 1: lr1.md
  - Лабораторная 2: lr2.md
  - Лабораторная 3: lr3.md

theme:
  name: material
